/*
Copyright 2022 The OpenShift Pipelines Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift-pipelines/manual-approval-gate/pkg/apis/approvaltask/v1alpha1"
	approvaltaskv1alpha1 "github.com/openshift-pipelines/manual-approval-gate/pkg/client/clientset/versioned/typed/approvaltask/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeApprovalTasks implements ApprovalTaskInterface
type fakeApprovalTasks struct {
	*gentype.FakeClientWithList[*v1alpha1.ApprovalTask, *v1alpha1.ApprovalTaskList]
	Fake *FakeOpenshiftpipelinesV1alpha1
}

func newFakeApprovalTasks(fake *FakeOpenshiftpipelinesV1alpha1, namespace string) approvaltaskv1alpha1.ApprovalTaskInterface {
	return &fakeApprovalTasks{
		gentype.NewFakeClientWithList[*v1alpha1.ApprovalTask, *v1alpha1.ApprovalTaskList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("approvaltasks"),
			v1alpha1.SchemeGroupVersion.WithKind("ApprovalTask"),
			func() *v1alpha1.ApprovalTask { return &v1alpha1.ApprovalTask{} },
			func() *v1alpha1.ApprovalTaskList { return &v1alpha1.ApprovalTaskList{} },
			func(dst, src *v1alpha1.ApprovalTaskList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ApprovalTaskList) []*v1alpha1.ApprovalTask {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ApprovalTaskList, items []*v1alpha1.ApprovalTask) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
