/*
Copyright 2022 The OpenShift Pipelines Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisapprovaltaskv1alpha1 "github.com/openshift-pipelines/manual-approval-gate/pkg/apis/approvaltask/v1alpha1"
	versioned "github.com/openshift-pipelines/manual-approval-gate/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openshift-pipelines/manual-approval-gate/pkg/client/informers/externalversions/internalinterfaces"
	approvaltaskv1alpha1 "github.com/openshift-pipelines/manual-approval-gate/pkg/client/listers/approvaltask/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApprovalTaskInformer provides access to a shared informer and lister for
// ApprovalTasks.
type ApprovalTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() approvaltaskv1alpha1.ApprovalTaskLister
}

type approvalTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApprovalTaskInformer constructs a new informer for ApprovalTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApprovalTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApprovalTaskInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApprovalTaskInformer constructs a new informer for ApprovalTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApprovalTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenshiftpipelinesV1alpha1().ApprovalTasks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenshiftpipelinesV1alpha1().ApprovalTasks(namespace).Watch(context.TODO(), options)
			},
		},
		&apisapprovaltaskv1alpha1.ApprovalTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *approvalTaskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApprovalTaskInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *approvalTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisapprovaltaskv1alpha1.ApprovalTask{}, f.defaultInformer)
}

func (f *approvalTaskInformer) Lister() approvaltaskv1alpha1.ApprovalTaskLister {
	return approvaltaskv1alpha1.NewApprovalTaskLister(f.Informer().GetIndexer())
}
